packages:
  - packages/*
  - '!packages/api'
  - packages/api/*
  - '!packages/api/client'
  - packages/api/client/*
  - '!packages/msar'
  - packages/msar/*
  - '!packages/oauth2-cli'
  - packages/oauth2-cli/*

ignoredBuiltDependencies:
  - '@parcel/watcher'

onlyBuiltDependencies:
  - gifsicle
  - jpegtran-bin
  - nx
  - optipng-bin
  - sharp
