publicHoistPattern:
  - '*prettier*'
  - '*eslint*'

minimumReleaseAgeExclude:
  - '@groton/colors@0.4.3'

allowBuilds:
  '@parcel/watcher': true
  gifsicle: true
  jpegtran-bin: true
  nx: true
  optipng-bin: true
  sharp: true

packages:
  - packages/*
  - '!packages/api'
  - packages/api/*
  - '!packages/api/client'
  - packages/api/client/*
  - '!packages/msar'
  - packages/msar/*
  - '!packages/oauth2-cli'
  - packages/oauth2-cli/*
