packages:
  - packages/*
  - '!packages/api'
  - packages/api/*
  - '!packages/api/client'
  - packages/api/client/*
  - '!packages/msar'
  - packages/msar/*
  - '!packages/oauth2-cli'
  - packages/oauth2-cli/*

allowBuilds:
  '@parcel/watcher': true
  gifsicle: true
  jpegtran-bin: true
  nx: true
  optipng-bin: true
  sharp: true

minimumReleaseAgeExclude:
  - '@groton/colors@0.4.3'

publicHoistPattern:
  - '*prettier*'
  - '*eslint*'
