packages:
  - 'packages/*'
  - '!packages/canvas-cli'
  - 'packages/canvas-cli/*'
  - '!packages/canvas-cli/client'
  - 'packages/canvas-cli/client/*'
  - '!packages/msar'
  - 'packages/msar/*'
  - '!packages/oauth2-cli'
  - 'packages/oauth2-cli/*'
