import { JSONObject, JSONValue } from '@battis/typescript-tricks';
import { client, Masquerade } from '#client';
import { DeveloperKey } from '../../../../Resources/DeveloperKeys.js';

export type createPathParameters = {
  /**
   * ID
   *
   * type: string
   *
   *
   */
  account_id: string | number;
};

export type createSearchParameters = Masquerade;

export type createFormParameters = Masquerade & {
  /**
   * no description
   *
   * json
   *
   *
   */
  developer_key: JSONObject;
  /**
     * Defaults to false. If true, access tokens
generated by this key will expire after 1 hour.
     *
     * type: boolean
     *
     * 
     */
  'developer_key[auto_expire_tokens]': boolean | string;
  /**
   * Contact email for the key.
   *
   *
   *
   *
   */
  'developer_key[email]': string;
  /**
   * URL for a small icon to display in key list.
   *
   *
   *
   *
   */
  'developer_key[icon_url]': string;
  /**
   * The display name.
   *
   *
   *
   *
   */
  'developer_key[name]': string;
  /**
   * User-provided notes about the key.
   *
   *
   *
   *
   */
  'developer_key[notes]': string;
  /**
   * Deprecated in favor of redirect_uris. Do not use.
   *
   *
   *
   *
   */
  'developer_key[redirect_uri]': string;
  /**
     * List of URLs used during OAuth2 flow to validate
given redirect URI.
     *
     * 
     *
     * 
     */
  'developer_key[redirect_uris]': JSONValue;
  /**
   * User-specified code representing the vendor that uses the key.
   *
   *
   *
   *
   */
  'developer_key[vendor_code]': string;
  /**
   * Defaults to true. If false, key will not be visible in the UI.
   *
   * type: boolean
   *
   *
   */
  'developer_key[visible]': boolean | string;
  /**
     * Defaults to false. If true, key is only usable in
non-production environments (test, beta). Avoids problems with beta refresh.
     *
     * type: boolean
     *
     * 
     */
  'developer_key[test_cluster_only]': boolean | string;
  /**
     * Used in OAuth2 client credentials flow to
specify the audience for the access token.
     *
     * 
     *
     * 
     */
  'developer_key[client_credentials_audience]': string;
  /**
   * List of API endpoints key is allowed to access.
   *
   *
   *
   *
   */
  'developer_key[scopes]': JSONValue;
  /**
   * If true, then token requests with this key must include scopes.
   *
   * type: boolean
   *
   *
   */
  'developer_key[require_scopes]': boolean | string;
  /**
     * If true, allows &#x60;includes&#x60; parameters in API requests that
match the scopes of this key.
     *
     * type: boolean
     *
     * 
     */
  'developer_key[allow_includes]': boolean | string;
};

type Options = (
  | {
      path: createPathParameters;
    }
  | {
      /** @deprecated Use {@link Options.path} */
      pathParams: createPathParameters;
    }
) &
  (
    | {
        query?: Partial<createSearchParameters>;
        /** @deprecated Use {@link Options.query} */
        searchParams?: Partial<createSearchParameters>;
        body?: Partial<createFormParameters>;
        /** @deprecated Use {@link Options.body} */
        params?: Partial<createFormParameters>;
        strict?: false;
      }
    | ((
        | {
            query: createSearchParameters;
          }
        | {
            /** @deprecated Use {@link Options.query} */
            searchParams: createSearchParameters;
          }
      ) &
        (
          | {
              body: createFormParameters;
            }
          | {
              /** @deprecated Use {@link Options.body} */
              params: createFormParameters;
            }
        ) & {
          strict: true;
        })
  );

/**
 * Create a Developer Key
 *
 * Create a new Canvas API key. Creating an LTI 1.3 registration is not supported here and
should be done via the LTI Registration API.
 *
 * nickname: create_developer_key
 *
 * 
 *
 * 
 */
export async function create(options: Options) {
  const response = await client().fetchAs<DeveloperKey>(
    `/api/v1/accounts/{account_id}/developer_keys`,
    {
      method: 'POST',
      ...options
    }
  );
  return response;
}
