import { client, Masquerade } from '#client';
import { JSONValue } from '@battis/typescript-tricks';

export type find_last_summary_coursesPathParameters = {
  /**
   * ID
   *
   * Type: string
   */
  course_id: string | number;
  /**
   * ID
   *
   * Type: string
   */
  topic_id: string | number;
};

export type find_last_summary_coursesSearchParameters = Masquerade;

type Options = (
  | {
      path: find_last_summary_coursesPathParameters;
    }
  | {
      /** @deprecated Use {@link Options.path} */
      pathParams: find_last_summary_coursesPathParameters;
    }
) &
  (
    | {
        query?: Partial<find_last_summary_coursesSearchParameters>;
        /** @deprecated Use {@link Options.query} */
        searchParams?: Partial<find_last_summary_coursesSearchParameters>;
        strict?: false;
      }
    | ((
        | {
            query: find_last_summary_coursesSearchParameters;
          }
        | {
            /** @deprecated Use {@link Options.query} */
            searchParams: find_last_summary_coursesSearchParameters;
          }
      ) & {
        strict: true;
      })
  );

/**
 * Find Last Summary
 *
 * Returns: (1) last userInput (what current user had keyed in to produce the
 * last discussion summary), (2) last discussion summary generated by the
 * current user for current discussion topic, based on userInput, (3) and some
 * usage information.
 *
 * Nickname: find_last_summary_courses
 */
export async function find_last_summary_courses(options: Options) {
  const response = await client().fetchAs<JSONValue>(
    `/api/v1/courses/{course_id}/discussion_topics/{topic_id}/summaries`,
    {
      method: 'GET',
      ...options
    }
  );
  return response;
}
