import { Masquerade } from '@groton/canvas-cli.client.base';
import { client } from '../../../../../Client.js';

export type find_last_summary_groupsPathParameters = {
  /** ID */
  group_id: string;
  /** ID */
  topic_id: string;
};

export type find_last_summary_groupsSearchParameters = Masquerade;

type Options = {
  pathParams: find_last_summary_groupsPathParameters;
} & (
  | {
      searchParams?: Partial<find_last_summary_groupsSearchParameters>;
      strict?: false;
    }
  | {
      searchParams: find_last_summary_groupsSearchParameters;
      strict: true;
    }
);

/**
 * Find Last Summary
 *
 * Returns: (1) last userInput (what current user had keyed in to produce the
 * last discussion summary), (2) last discussion summary generated by the
 * current user for current discussion topic, based on userInput, (3) and some
 * usage information.
 *
 * Nickname: find_last_summary_groups
 */
export async function find_last_summary_groups(options: Options) {
  const response = await client().fetchAs<void>(
    `/api/v1/groups/{group_id}/discussion_topics/{topic_id}/summaries`,
    {
      method: 'GET',
      ...options
    }
  );
  return response;
}
