import { Masquerade } from '@groton/canvas-cli.client.base';
import { client } from '../../../../../Client.js';

export type find_last_summary_coursesPathParameters = {
  /**
   * ID
   *
   * Type: string
   */
  course_id: string | number;
  /**
   * ID
   *
   * Type: string
   */
  topic_id: string | number;
};

export type find_last_summary_coursesSearchParameters = Masquerade;

type Options = {
  pathParams: find_last_summary_coursesPathParameters;
} & (
  | {
      searchParams?: Partial<find_last_summary_coursesSearchParameters>;
      strict?: false;
    }
  | {
      searchParams: find_last_summary_coursesSearchParameters;
      strict: true;
    }
);

/**
 * Find Last Summary
 *
 * Returns: (1) last userInput (what current user had keyed in to produce the
 * last discussion summary), (2) last discussion summary generated by the
 * current user for current discussion topic, based on userInput, (3) and some
 * usage information.
 *
 * Nickname: find_last_summary_courses
 */
export async function find_last_summary_courses(options: Options) {
  const response = await client().fetchAs<void>(
    `/api/v1/courses/{course_id}/discussion_topics/{topic_id}/summaries`,
    {
      method: 'GET',
      ...options
    }
  );
  return response;
}
